Fix `NoClassDefFoundError: java/lang/constant/Constable` with JDK 12 This seems like a bug with the compiler: when compiling with JDK 12 with Java 8 target, this will cause a `NoClassDefFoundError: java/lang/constant/Constable` when running on Java 8, even even though `Constable` was added in Java 12, so the compiler should not use it when compiling with Java 8 target.